Simplify sanity checks
Not everyone has lsof and this other fancy stuff.
Just check for the existence of "id". In case the user runs the
script on a dead ratox-folder, it will error out sooner or later
anyway.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -22,3 +22,10 @@ function stdin_trasher () {
 	{ cat > /dev/null <&3 3<&- & } 3<&0
 	echo $!
 }
+
+function check_if_dir() {
+	if ! test -e id; then
+		echo "ERROR: Is this a ratox directory?" >&2
+		exit 1
+	fi
+}
